### ISSUE TITLE
some features

### ISSUE THREAD

**Issue by teddyxlandlee** [Xdi8Mod/Xdi8aho-Mod#3]
Here are some designs requesting:
- [x] #4
- [x] what about common bottles? _NO_
- [x] Is there any limit? _(maybe 5 in 1)_
- [x] should fireflies follow their owner(s) who released them? _(owners released in 1h who locked them inside for 20min or more)_
- [x] how do they spawn & despawn? I haven't written anything about mob spawning, which might need your help
- [x] call somebody for hooking fonts as soon as possible

I'm busy these weeks, so don't call me from 22 June to 26 June. thx

**Comment by QWERTY770** [comment]
My opinion:

1. Fireflies should be collected in tinted glass bottles. But more than 3 fireflies(maybe 5) can be collected in a bottle, since they are tiny.
2. I have no idea about request 4. What's your opinion?
3. I wrote something about mob spawning last year, but that didn't work well. The reason is unknown. (see github.com/QWERTY770/MCBBS-Wiki-Mod)
4. Some of my classmates have given me suggestions of the mod and I will send their suggestions to you this weekend.

Thanks.

**Comment by teddyxlandlee** [comment]
Opinion for request 4:  
A firefly can recognize & follow one of its owners, who are not too far from it, have released it in 1h and have locked it inside for 20min or more.  
Technically, several NBT tags (type: LongTag) are used to store timestamps.
> Fireflies, carry light.    

So how do they "carry light" and make their owners' future bright?
